services:
  web:
    build:
      context: .
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    environment:
      - PORT=${PORT:-3000}
      - RAILS_ENV=${RAILS_ENV:-production}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-2}
      - RAILS_MAX_THREADS=${RAILS_MAX_THREADS:-5}
      - DATABASE_URL=${DATABASE_URL}
