services:
  web:
    build:
      context: .
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "bundle install && bundle exec puma -C /app/config/puma.rb "
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    environment:
      - PORT=${PORT:-4004}
      - RAILS_ENV=${RAILS_ENV:-production}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - WEB_CONCURRENCY=${WEB_CONCURRENCY}
      - RAILS_MAX_THREADS=${RAILS_MAX_THREADS}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_POOL=${DATABASE_POOL}
