default: &default
  encoding: utf8
  adapter: <%= ENV["DB_ADAPTER"] || "mysql2" %>
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
